[env:nucleo_wl55jc]
extends = stm32_base
board = nucleo_wl55jc
board_upload.maximum_size = 233472 ; reserve the last 28KB for filesystem
build_flags =
  ${stm32_base.build_flags}
  -Ivariants/stm32/nucleo_wl55jc
  -DSERIAL_UART_INSTANCE=1
  -DPIN_SERIAL_RX=PA2
  -DPIN_SERIAL_TX=PA3
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -DMESHTASTIC_EXCLUDE_AIR_QUALITY_SENSOR=1
  -DMESHTASTIC_EXCLUDE_POWER_TELEMETRY=1
  -DMESHTASTIC_EXCLUDE_BLUETOOTH=1
  -DMESHTASTIC_EXCLUDE_WIFI=1
  -DMESHTASTIC_EXCLUDE_ETHERNET=1
  -DMESHTASTIC_EXCLUDE_GPS=1
  -DMESHTASTIC_EXCLUDE_MODULES=1
  -DMESHTASTIC_EXCLUDE_MQTT=1
  -DPRIVATE_HW

upload_port = stlink
